export interface Employees {
    empId: string;
    name: string;
    empCode: string;
    status: string;
    empGroupId: string;
    companyId: string;
    designationId: string;
    gender: string;
    bloodGroup: string;
    contactNumber1: string;
    contactNumber2: string;
    addressId: string;
    createdDate: string;
    modifiedDate: string;
    createdBy: string;
    modifiedBy: string;
    dateOfJoin: string;
    dateOfLeaving: string;
    shiftId: string;
    dob: string;
    emergencyId: string;
    father: string;
    mother: string;
    firstName: string;
    lastName: string;
    empGroupName: string;
    empDesignationName: string;
}
