export interface Orders {
    cust_ID: string;
    customer_NAME: string;
    delivery_DISTANCE: string;
    laying_COST: string;
    loading_UNIT_COST: string;
    note: string;
    order_CREATED_BY: string;
    order_CREATED_DT: string;
    order_DT: string;
    order_GROUP_NO: string;
    order_MODIFIED_DT: string;
    order_STATUS: string;
    product_GROUP: string;
    product_ID: string;
    product_NAME: string;
    product_UNIT_COST: string;
    referrel1_ID: string;
    refrerel2_ID: string;
    refrerel1_NAME: string;
    refrerel2_NAME: string;
    sales_REP_ID: string;
    sales_REP_NAME: string;
    site_ID: string;
    site_NAME: string;
    sqft_LAYING_COST: string;
    sqft_LOADING_COST: string;
    sqft_TRANSPORT_COST: string;
    sqft_UNIT_COST: string;
    status_FLAG: string;
    subOrders: string;
    tax1: string;
    tax2: string;
    taxable_STATUS: string;
    total_COST: string;
    total_LAYING_COST: string;
    total_LOADING_COST: string;
    total_ORDER_UNIT: string;
    total_PRODUCT_COST: string;
    total_TAX1: string;
    total_TAX2: string;
    total_TRANSPORT_COST: string;
    transport_KM_COST: string;
    uom: string;
    uom_ID: string;
    // aggregateOrderModifiedBy: string;
    // aggregateOrderModifiedDate: string;
    // aggregateOrderStatus: string;
    // customerId: string;
    // deliveryDistance: string;
    // loadingType: string;
    // loadingUnitCost: string;
    // orderCreatedBy: string;
    // orderCreatedDate: string;
    // orderDate: string;
    // orderGroupNo: string; 
    // orderModifiedDate: string;
    // orderNumber: string;
    // orderStatus: string;
    // productId: string;
    // productUnitCost: string;
    // referel1Id: string;
    // referer2Id: string;
    // refererId: string;
    // salesRepId: string;
    // siteId: string;
    // totalCost: string;
    // totalOrderUnit: string;
    // transportCost: string;
    // unit: string;
    // weight: string;
}